services:
  web:
    image: kubedevio/simulador-do-caos:v1
    ports:
      - 8080:3000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    #cpuset: "0"
    memswap_limit: 512M
    deploy:
      resources:
        limits:
            cpus: "0.5"
            memory: 512M
